### ISSUE TITLE
Login/Register/Logout button should depict the state of the user. 

### ISSUE THREAD

**Issue by srijit10** [ajalan065/DiFo#18]
Logout button should appear only when someone is logged in.
Logout button should not appear in this image shown below:
![screenshot1](https://cloud.githubusercontent.com/assets/13488642/24580104/11ef10ba-1720-11e7-8114-a6248a18bddc.png)

**Comment by archie94** [comment]
Added to that when we are logged in the Login/Register button should display Logout.

**Comment by archie94** [comment]
You may send a PR on this @srijit10

**Comment by archie94** [comment]
Closed via #23
