### ISSUE TITLE
UI bugs 

### ISSUE THREAD

**Issue by archie94** [ajalan065/DiFo#27]
There are some disturbing UI bugs, introduced after 23d5fc4c826b3b807e6685157ae41f3ca29f187c. 

Steps to reproduce : 

- Before logging in every thing seems fine. We have a window like 
![1](https://cloud.githubusercontent.com/assets/12955150/24656514/7f82f0a0-1960-11e7-8dcc-44e25cd538f1.png)

- However after changing tabs notice that the **input field tends to stick to the bottom of every page**. **Also notice the url. It ends with `chats.html`**.
![2](https://cloud.githubusercontent.com/assets/12955150/24656618/d7df8dee-1960-11e7-8523-3dd8b8c02f60.png)
So now reloading will drop me to the chat window which is obviously undesired. Also notice the **title of the page**. It is `HTML Frames` for some reason :P .

- Same scenario when I move to the Home tab. 
![3](https://cloud.githubusercontent.com/assets/12955150/24656707/1ccf9ab6-1961-11e7-8c5b-fbe4eedb367d.png)

- And even in the profile tab. 
![4](https://cloud.githubusercontent.com/assets/12955150/24656723/2d4ebb38-1961-11e7-8b92-7079a20187ff.png)

Also the **url of the project** seems to have changed to `localhost:port_num/disforum` . Please revert that back to `localhost:port_num/DiFo`.

**Comment by archie94** [comment]
@ajalan065 could you please look into these ?

**Comment by ajalan065** [comment]
#fixed
